import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";
import ReactLenis from "lenis/react";
import { CursorProvider } from "@/lib/hooks/useCursorProvider";
import { inter, satoshi, satoshiVariable } from "@/lib/fonts";
import { PageRevealer } from "@/components/animate-components/PageRevealer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="es">
        <ReactLenis root>
          <CursorProvider>
            <body
              className={`${inter.variable} ${satoshi.variable} ${satoshiVariable.variable} font-inter bg-background text-foreground antialiased`}
            >
              <PageRevealer />

              <div>{children}</div>
            </body>
          </CursorProvider>
        </ReactLenis>
      </html>
    </ViewTransitions>
  );
}
